### ISSUE TITLE
Play2Die

### ISSUE THREAD

**Issue by rsodre** [funDAOmental/pistols#11]
Implement [Play2Die](https://mirror.xyz/0x8046108b92EEAa28b8970B6294BfD432dc382c7D/B5cc1Fjwuc05XGEogFug7HtR9IjpJsN6N25eEnIgw4A) mechanics.

When a new challenge is created, the Challenger can stake a certain amount of tokens that need to be matched by the Challenged when accepting the challenge. The winner wins the full pot, less a the developer's fee.

- [x] Stake tokens from Challenger and Challenged to the smart contract
- [x] Ability to stake $LORDS
- [x] Ability to stake any erc-20
- [ ] Ability to stake any erc-721
- [x] Distribute the full amount of tokens back to players if the challenge is canceled for any reason
- [x] Transfer the full amount to duel winners, less developer fee
- [x] On a draw, distribute staked tokens back to players, less developer fee
- [x] How much is the developer fee?
- [x] Ability to configure developer fee on the smart contract

**Comment by Rob-Morris** [comment]
Developer fee should be 4 LORDS or 10% of the overall stake, whichever is higher, and potentially with an arbitrary fixed fee of N for any non-fungible token. Fee distribution should be:
* 25% to us
* 25% to realms
* 25% to client
* 25% to player with best score (score method TBC)

**Comment by rsodre** [comment]
Closed by #22
