### ISSUE TITLE
Request: Refresh button on the tavern page

### ISSUE THREAD

**Issue by LordSquiddy** [funDAOmental/pistols#15]
I've noticed that sometimes (maybe I'm just impatient) when someone has DM'd me saying they have accepted the duel, the tavern page doesn't update this until a total reload (which feels a little dirty to me). Thoughts on possibly an on-page tavern reload button?

**Comment by LordSquiddy** [comment]
Closing this - I was just being impatient, the UI updates itself quickly enough.

**Comment by rsodre** [comment]
All the UI is made of recs hooks, should be updated automatically.
